---
- hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  tasks:
    - name: stop containers
    # get all host names from inventory
      loop: "{{ groups['all'] }}"
    # use lxd_container module from ansible to create containers
      lxd_container:
      # container name is the hostname
        name: "{{ item }}"
        state: stopped
    - name: delete containers
      # get all host names from inventory
      loop: "{{ groups['all'] }}"
      # use lxd_container module from ansible to create containers
      lxd_container:
        # container name is the hostname
        name: "{{ item }}"
        state: absent


