

- hosts: localhost
  become: yes
  # become_method: sudo
  become_user: gk
  vars:
     helm_chart_url: "https://fluent.github.io/helm-charts"
  tasks:
   - name: Add helm repo fluent
     kubernetes.core.helm_repository:
      name: fluent
      repo_url: "{{ helm_chart_url }}"


- hosts: localhost
  become: yes
  # become_method: sudo
  become_user: gk
  tasks:
     - name: Create a k8s namespace  logging
       kubernetes.core.k8s:
        name: logging
        api_version: v1
        kind: Namespace
        state: present

     - name: Install fluent-bit
       kubernetes.core.helm:
         name: fluent-bit
         namespace: logging
         chart_ref: fluent/fluent-bit
        #  state: absent
        #  values:
        #    configInline:
        #     address-pools:
        #     - name: default
        #       protocol: layer2
        #       addresses:
        #       - 10.82.54.240-10.82.54.250