- hosts:
  - kmaster
  become: yes
  become_method: sudo
  tasks:
    - name: copies admin.conf to local user's kube config
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: /home/gk/.kube/config
        remote_src: yes
        owner: gk
        flat: yes