---
- hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  tasks:
    - name: stop containers
    # get all host names from inventory
      loop: "{{ groups['all'] }}"
    # use lxd_container module from ansible to create containers
      lxd_container:
      # container name is the hostname
        name: "{{ item }}"
        state: stopped
    - name: delete containers
      # get all host names from inventory
      loop: "{{ groups['all'] }}"
      # use lxd_container module from ansible to create containers
      lxd_container:
        # container name is the hostname
        name: "{{ item }}"
        state: absent



- hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  tasks:
    - name: Create a started container
      with_items: "{{ groups['all'] }}"
      lxd_container:
        name: "{{ item }}"
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: simplestreams
          alias: ubuntu/xenial/amd64
        profiles: ["k8s"]
        wait_for_ipv4_addresses: true
        # timeout: 600
        config:
        devices:
          # configure network interface
          eth0:
            type: nic
            nictype: bridged
            parent: lxdbr0
            # get ip address from inventory
            ipv4.address: "{{ hostvars[item].ip_address }}"

