

- hosts: localhost
  become: yes
  # become_method: sudo
  become_user: gk
  vars:
     helm_chart_url: "https://kubernetes.github.io/ingress-nginx"
  tasks:
   - name: Add helm repo ingress-nginx
     kubernetes.core.helm_repository:
      name: ingress-nginx
      repo_url: "{{ helm_chart_url }}"


- hosts: localhost
  become: yes
  # become_method: sudo
  become_user: gk
  tasks:
     - name: Create a k8s namespace  ingress-nginx
       kubernetes.core.k8s:
          name: ingress-nginx
          api_version: v1
          kind: Namespace
          # state: absent

     - name: Install nginx-ingress
       kubernetes.core.helm:
         name: ingress-nginx
         namespace: ingress-nginx
         chart_ref: ingress-nginx/ingress-nginx
        #  state: absent
         values:
          ## IngressClass resources are supported since k8s >= 1.18 and required since k8s >= 1.19
            ingressClassResource:
              default: true



