- hosts: localhost
  become: yes
  # become_method: sudo
  become_user: gk
  tasks:
      - name: Create a k8s namespace  ingress-nginx
        kubernetes.core.k8s:
          name: ingress-nginx
          api_version: v1
          kind: Namespace
          state: present

      - name: Download ingress-nginx manifest to the cluster.
        ansible.builtin.get_url:
          url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.1/deploy/static/provider/cloud/deploy.yaml
          dest: ~/ingress-nginx.yaml
          mode: '0664'

      - name: Apply ingress-nginx manifest to the cluster.
        kubernetes.core.k8s:
          state: present
          src: ~/ingress-nginx.yaml
          namespace: ingress-nginx


