- hosts: localhost
  become: yes
  become_method: sudo
  become_user: gk
  vars:
     helm_chart_url: "https://prometheus-community.github.io/helm-charts"
  tasks:
   - name: Add helm repo prometheus-community
     kubernetes.core.helm_repository:
      name: prometheus-community
      repo_url: "{{ helm_chart_url }}"


- hosts: localhost
  become: yes
  become_method: sudo
  become_user: gk
  tasks:
     - name: Create a k8s namespace  prometheus
       kubernetes.core.k8s:
        name: prometheus
        api_version: v1
        kind: Namespace
        state: present

     - name: Install prometheus
       kubernetes.core.helm:
         name: prometheus-stack
         namespace: prometheus
         chart_ref: prometheus-community/kube-prometheus-stack
        #  state: absent
        #  values:
